# Generated by Django 4.2.5 on 2023-09-26 16:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images')),
                ('shortDescription', models.TextField(max_length=300)),
                ('description', models.TextField(max_length=100000)),
                ('category', models.IntegerField(choices=[(1, 'سیاست'), (2, 'فرهنگ و هنر'), (3, 'اقتصاد'), (4, 'جهان'), (5, 'ورزش'), (6, 'جنگ نرم'), (7, 'جهاد و مقاومت'), (8, 'بازار'), (9, 'دفاع و امنیت')], default=1)),
                ('dateOfRelease', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
