# Generated by Django 4.2.5 on 2023-09-26 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsmodel',
            name='category',
        ),
        migrations.RemoveField(
            model_name='newsmodel',
            name='dateOfRelease',
        ),
        migrations.RemoveField(
            model_name='newsmodel',
            name='image',
        ),
    ]
