# Generated by Django 4.2.3 on 2023-09-28 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NewsApp', '0002_remove_newsmodel_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='news', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
